name: Pelican site CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - gh-pages

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Change ownership
      run: sudo chown -R $USER:$USER .
    - uses: actions/checkout@v3
    - uses: nelsonjchen/gh-pages-pelican-action@0.1.5
      env:
        GITHUB_TOKEN: ${{secrets.ACTION_TOKEN}}
